[build]
  command = "gatsby build"
  publish = "public"

[build.environment]
  NODE_VERSION = "18.17.0"
  GATSBY_CONCURRENT_DOWNLOAD = "25"

[[plugins]]
  package = "@netlify/plugin-gatsby"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:;"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

[functions]
  directory = "functions"
